### PR TITLE
Capture telemetry to detect feature usage and crashes

### PR DESCRIPTION
**Pull request by DonJayamanne**
This feature can be turned off as documented here https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting

### CODE REVIEW

**Comment by ole1986** [comment]
Can I also access the results?

**Comment by ole1986** [comment]
```
    ERROR in /home/ole.koeckemann/gitHistoryVSCode/src/adapter/repository/gitBranchService.ts
    /home/ole.koeckemann/gitHistoryVSCode/src/adapter/repository/gitBranchService.ts
    [tsl] ERROR in /home/ole.koeckemann/gitHistoryVSCode/src/adapter/repository/gitBranchService.ts(6,1)
          TS6133: 'StopWatch' is declared but its value is never read.
```

**Comment by DonJayamanne** [comment]
> Can I also access the results?

Not yet, but that is most certainly the plan. Without a doubt.

**Comment by ole1986** [comment]
Since this is implement do we need to inform the user about fetching such telemetry data or is it covered with vscode?

**Comment by DonJayamanne** [comment]
It is covered with VSCode and gets disabled when user turns off telemetry.

**Comment by DonJayamanne** [comment]
> Otherwise I would release version 0.6.3 today

Let's do this, thanks

**Pull request merged**
