### PR TITLE
History tags

### PR DESCRIPTION
**Pull request by ole1986**
Once this PR is applied it shows the HEAD and remote info when doing "git log"

githistoryvscode-tags

### CODE REVIEW

**Comment by ole1986** [comment]
Mhm... is it not useful enough to merge?

**Comment by DonJayamanne** [comment]
@mikes-gh
What do you think about this?
Looks fairly simple and makes sense. I have tested this locally and it works.

**Comment by mikes-gh** [comment]
Looks good - a couple of sugestions.

Probably should htmlEncode the content of the tags to be on safe side.
Just in case someone adds a tag "Rock & Roll" for example.
I had to bug fix #53 for that.

I would prefer more muted colours or a more themed look but I guess thats subjective.

**Comment by mikes-gh** [comment]
@ole1986 Looks good to me.
Could you squash and rebase please.

**Comment by ole1986** [comment]
Done

**Comment by DonJayamanne** [comment]
Thanks everyone

**Comment by ikkala** [comment]
Hi, When does the version 0.2.1 containing this feature come available to marketplace?

**Pull request merged**
