### PR TITLE
Improve style of logs, details and error views

### PR DESCRIPTION
**Pull request by kumarharsh**
Hi @DonJayamanne 

I find the git history tool to be very useful, but I felt that didn't *look* very good. This PR is a try to improve the UI.
It also fixes some issues with css like:
0. renamed classes to follow the kebab-case convention, and remove some extra wrapping divs, etc.
1. removed unused css
2. dedupe classes on parent and child
3. rework layout for some components
4. create a new diff visualization for files in details view

Most of the changes are incremental, and I've taken care that nothing breaks.

There is still work to be done, such as handling some cases where the graph renders crooked, like in this image:
vscode

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@kumarharsh, wow, thanks for the great PR. Will look into this and merge it soon.

**Comment by kumarharsh** [comment]
@donjayamanne did you get a chance to look at it?

**Comment by DonJayamanne** [comment]
Will look into this today, sorry

**Comment by DonJayamanne** [comment]
@kumarharsh , looks freekin awesome 👍 . Thanks

**Comment by DonJayamanne** [comment]
@kumarharsh , will try to wrap everything using webpack and standard html code without the hacky injection in onload.
The problem was standard scripts didn't seem to work in earlier versions of VS Code.
I'm certain they were being stripped off. Anyways, not that its ok, I should be able to make it simpler by referencing standard scripts.

**Comment by DonJayamanne** [comment]
@kumarharsh , found a few bugs.
- Clicking an item causes the view to scroll to the top (only happens the first time)
- If the comments are very long, then the copy (blue) box is on the right
   + Ideally the comments should get truncated (with ellipsis) - that's what used to happen

These will need to be fixed before the next release. Hopefully you can look into them. Pity I didn't find them before the merge.

Thanks again.

**Comment by kumarharsh** [comment]
@DonJayamanne thanks :) I'll look into it this week.

**Comment by DonJayamanne** [comment]
@kumarharsh , i think it would be easier if we tracked them as issues. Lets leave this PR. 
Thanks

**Comment by kumarharsh** [comment]
Sure. Actually a problem I faced while doing these changes are that it's impossible to debug the UI rendered in vscode due to it being inside a sandboxed webview or something. Can you suggest something in that respect?

**Comment by DonJayamanne** [comment]
Take the html and save it into a file
heres the line that needs to be modified to take the html and save it into a file.
Then just launch the html file in chrome and debug.

https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/logViewer/main.ts#L31

**Comment by kumarharsh** [comment]
@DonJayamanne ah, didn't think of that. super!

**Comment by DonJayamanne** [comment]
@kumarharsh , you've been given credit on the readme page, thanks for the wonderful work.

**Comment by kumarharsh** [comment]
thank you :)

**Pull request merged**
