### PR TITLE
General Code Cleanup

### PR DESCRIPTION
**Pull request by mikes-gh**
This pull request is rather noisy sorry but I think it needs doing.

Changes

- Add tslint as a dev dependency
- Pass tslint as per tslint.json
- Add tslint to prepublish.
- Enforce strict null checking
- Add some additional nice tsc checks

Bugs

- In the course of enforcing strict null checking I discovered a bug in the tmpFileCleanup code.
I checked my temp directory and indeed temp files were not being deleted.
This is due to the way vscode presents the URI of the temp file as a lowercase of the drive letter.
However when adding the cleanup map the file was being added with a capital drive letter.
To fix we lowercase the drive letter before adding it to the cleanup function map.

### CODE REVIEW

**Comment by mikes-gh** [comment]
BTW I found out in github add `?w=1` to the end of diff view to filter out whitespace.
Useful for this PR

**Comment by mikes-gh** [comment]
Beware any scoping bugs from previous abuse of var.

**Comment by mikes-gh** [comment]
I had a good look through and I think all the variable scopes seem fine.

**Comment by mikes-gh** [comment]
@DonJayamanne  Id like to address a few issues in this repo but this needs to happen first as it will produce lots of merge conflicts if done afterwards.  Are you ok with this in pricipal?

**Comment by mikes-gh** [comment]
Oh sorry one more thing.  Do you have time to test.  I know I have push access now but doesn't hurt to have another pair of eyes on this.

**Comment by DonJayamanne** [comment]
I will test  this weekend

**Comment by mikes-gh** [comment]
Thanks

**Comment by DonJayamanne** [comment]
FYI - I have started looking into this.

**Comment by mikes-gh** [comment]
How are you getting on 😄

**Comment by mikes-gh** [comment]
Not sure how the last commit got missed.
A good argument for turning on the type checking options.

**Comment by DonJayamanne** [comment]
Yup, all looking good.
Will build, test and publish.

**Comment by DonJayamanne** [comment]
Great work in cleaning it up. Thanks

**Pull request merged**
