### PR TITLE
When current folder is not a GIT root folder, need to detect correct …

### PR DESCRIPTION
**Pull request by malytskyy**
…root. Otherwise detailed view can't show details.

### CODE REVIEW

**Comment by mikes-gh** [comment]
Looks good to me.
This PR has highlighted that the indentation and chaining in this file is a bit messy.
Maybe prefer catch to `.then(() => { },error function)` .

However this PR is consistent with the current coding style so lets push this first and cleanup later.

TODO refactor some of these anonymous functions to actual functions to improve readability.

**Comment by mikes-gh** [comment]
I added some comment but dont take it personally.  Youre working on stuff thats a bit of a mess.
We can push this whatever really and do a proper job later.
Thanks for this

**Comment by malytskyy** [comment]
hey, no problem! was just rather a quick fix :)

**Comment by mikes-gh** [comment]
Reopening - We'll still push this.
The formatting can wait.

**Comment by malytskyy** [comment]
whoops, wrong button pressed - please feel free to change the request however you find it appropriate.

**Comment by mikes-gh** [comment]
Yes that bit of code has at the very top

`// TODO:Clean up this mess` :smile: 

But your input is very much appreciated and we'll put this in.

**Comment by mikes-gh** [comment]
Could you 

git reset --hard HEAD~
git push --force

And well take just the first commit.

**Comment by mikes-gh** [comment]
Ok I just tested this and I get

`fatal: Not a git repository (or any of the parent directories): .git`

Without the change all ok.

So dont pull this yet

**Comment by mikes-gh** [comment]
Sorry I'll have to close this as untested.
 
historyUtil.getGitRepositoryPath(vscode.workspace.rootPath)

will return the path below vscode.workspace.rootPath

This wont work

**Comment by malytskyy** [comment]
hi, 

Suppose I have git repo (windows):

`D:\A\.git`

if I open the folder 

`D:\A\B\C`

then one needs to determine correct git root (`D:\A `instead of `D:\A\B\C`) for operations where one uses relative paths. 

The fix described case. Do you have an example where calling `getGitRepositoryPath` is problematic?

**Comment by mikes-gh** [comment]
Yes it doesn't work for the normal case where you open the root of the repo.
To test clone any repo and open the repo root.
Your code will return  an error since getGitRepositoryPath expects a file name and you are passing the workspace root.
If you opened the root of the repo (common senario) getGitRepositoryPath removes the first part of the path before searching the parents and won't find a valid git repo path.
https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/helpers/historyUtils.ts#L88

I'm guessing you only tested this on a senario where you opened a folder above the repo root.

**Pull request closed without merging**
