### PR TITLE
Replace extension icon with VSCode builtin history icon

### PR DESCRIPTION
**Pull request by tjx666**
screenshot_2020-11-08_23-57-17

### CODE REVIEW

**Comment by ole1986** [comment]
@tjx666 I think this is a good start to slowly give it some modern icons.

But when we change this icon it might also need to get changed on other places

**Comment by tjx666** [comment]
> @tjx666 I think this is a good start to slowly give it some modern icons.
> 
> But when we change this icon it might also need to get changed on other places

You means the close icon? Any others?

**Comment by ole1986** [comment]
@DonJayamanne what do you think about replacing the icon(s) with viscose native symbols?

**Review by DonJayamanne — APPROVED** [review]
I am fine with this change, and like it.
Would still prefer to keep the color icon on readme and product page.
If I'm not mistaken this only changes the icon inside VSCode .

**Comment by ole1986** [comment]
Below is just for internal notices, so we know how and what to use:
https://code.visualstudio.com/api/references/icons-in-labels

**Pull request merged**
