### PR TITLE
History for submodules in subdirectories

### PR DESCRIPTION
**Pull request by davehermann**
Provides history for submodules in subdirectories or nested in other submodules.
Resolves Issue #277.

This uses the now-available API in VS Code's built-in Git extension to get all detected repos in the workspace, and use their paths as the list of known repo paths.
[Per the API documentation](https://github.com/Microsoft/vscode/blob/master/extensions/git/README.md), the built-in Git's *[git.d.ts](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/api/git.d.ts)* file is included in this PR, but may be more logical to locate elsewhere for use throughout this extension.

I did also try scanning subdirectories per the existing method, but on a large directory hierarchy - like this extension - it's just too slow.  There are two commits in the PR, and the first one ([63fbdac](https://github.com/DonJayamanne/gitHistoryVSCode/commit/63fbdacbe4f2c4140c064509bcd5594840f333a4)) is that method if anyone is curious to work with it.

### CODE REVIEW

**Comment by ole1986** [comment]
I do like the idea of using its native git extension for it.
We should try to replace more with this instead of running the git cmd (through spawn/exec)

**Comment by DonJayamanne** [comment]
Damn, was supposed to review this. Will test on Tuesday and merge it.

**Comment by meierw** [comment]
Just wanted to check. What's going on with this feature? Would really like to see it implemented.

Also was thinking of writing some of my own features, like normalizing the fonts to match the VSCode settings, but dunno if I should, seeing as multiple Pull Requests are starting to get stale now...

**Comment by DonJayamanne** [comment]
Apologies, will get into them tonight

**Comment by ole1986** [comment]
I am going to move this into master branch with some amendments as we already use the git extension API in gitCommandExec.ts

So in future we can access the git extension api through:

```
// optional inject IGitCommandExecutor from contructor
constructor(@inject(IGitCommandExecutor) private gitCmdExecutor: IGitCommandExecutor) { }
// followed by
const git = this.gitCmdExecutor.gitExtension.getAPI(1);

```

Thanks for your work

**Pull request merged**
