### PR TITLE
Add Error Handlers for Spawned Processes

### PR DESCRIPTION
**Pull request by SE2Dev**

### CODE REVIEW

**Comment by mikes-gh** [comment]
This is a bit stale now anyway and doesnt seem to fix a a particualr issue.
Please add comment if this was for a particular senario.

**Comment by SE2Dev** [comment]
When I first installed gitHistoryVSCode, I had the git path in VSCode set to point to the version of git that was bundled with GitHub Desktop (Windows), and during the course of one of the updates the path to the bundled version of git was changed. At that point I had already installed Git for Windows and had added it to my system path - but forgot to update the path in the user settings in VSCode. For whatever reason VSCode itself was able to automatically use git while gitHistoryVSCode wasn't, however due to the lack of error handling for spawned processes the logs weren't incredibly helpful. I can't remember the specifics of the error, but by manually adding the error handlers I was able to better solve the issue.

**Comment by mikes-gh** [comment]
OK sounds like a good case.
Also can you make sure you you pass npm run lint as we are now using that to keep things tidy.
I cant reopen this as your repo is gone but well try to get this in

**Comment by mikes-gh** [comment]
Actually if you leave it with me I can add a PR as I have another in the pipeline and youd only end up rebasing again

**Comment by SE2Dev** [comment]
Yeah that'd be fine. The commit itself was small enough that it can easily be re-written anyway.

**Pull request closed without merging**
