### PR TITLE
Find Git for Windows installations

### PR DESCRIPTION
**Pull request by mad-mike**
Git for Windows's installer recommends not to put the git executables into the PATH environment variable. Therefore, 'git' will not be found when executed. The installer stores git's location in a registry key, however. This change will evaluate the registry on Windows systems and tries to find the full path to git.

### CODE REVIEW

**Comment by DonJayamanne** [comment]
Thanks for taking the time to identify a bug and proposing a fix. However as mentioned in a reply to another pull request of yours i've accepted another fix for the same issue. That seemed to have a better solution, by using the VSCode configuration settings. https://github.com/DonJayamanne/gitHistoryVSCode/commit/2998d7b0f7191a5bd17904cd3c74926b62694439

**Comment by mad-mike** [comment]
@DonJayamanne @zabel-xyz: Am I right in understanding that the git path in the configuration settings needs to be maintained manually, per workspace? If that is the case, I would like to ask you to reconsider and perhaps merge the two solutions.

**Comment by DonJayamanne** [comment]
HI Mike, I've tested this and from what I know about VSCode, we don't need to manually maintain the git path per workspace. I have VSCode on my MAC and Windows, and it works as expected, without having to configure anything. However if you can prove me wrong, I'm happy to reconsider your suggestions.

**Comment by mad-mike** [comment]
Hi @DonJayamanne,

the issue persists. You've obviously registered git in the path, so zabel-xyz's change doesn't apply in your setup.

In my setup, when I start the "Git: View History" command, I am prompted to select File or Line history, but no matter what I select, the dialog box just disappears without any feedback. As a user, I would simply assume the extension is broken and uninstall it.
Since I am a developer, I check the root cause. Node cannot find my git executable and thus cannot execute it. This is what I intended to report to users with #1 . Please be reminded that my setup is the default situation on Windows systems - I've double-checked the installer.
I then have to check the changelog to find out that since 0.0.3., git history can check the VS Code settings. After some searching, I find I can add a custom key named "git.path" to my user settings, which has to point to the exact location of git.exe. I try again after reloading the window and finally, I get some feedback. The output window tells me
```
fatal: Not a git repository (or any of the parent directories): .git
```
even though I know that my current workspace is versioned in git (after all, Code displays it to me in the git tab) and the file I had opened was added to the repository.

Please tell me: Is this how you expect the extension to work?

**Comment by DonJayamanne** [comment]
Hi Mike,
Thanks for testing this out. I guess this also means the standard GIT commands won't work in VS Code for you. Either way, i'm happy to merge your changes. Please could you re-submit your revised changes and i'll merge them in. If not, i'll manually add the changes, that cuz the code has change significantly and it is easier to just modify it to add the changes than merging. Thanks again.

**Comment by mad-mike** [comment]
That comment gave me an idea: Git _is_ working in VS Code, so somehow Code must be able to find it.
A little browsing gave me this https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/electron-browser/electronGitService.ts

Basically, what it checks is:
- Linux: PATH
- Mac: which command + some logic about XCode
- Windows: search in Program Files (first x64, then x86), finally try path

In my opinion, the best possible user experience is when the extension behaves exactly like the core app. Unfortunately, these classes and functions don't seem to be exposed to extensions.

**Comment by DonJayamanne** [comment]
Done, thanks

**Pull request closed without merging**
