### PR TITLE
Add exception handler when attempting to determine the `origin` remote

### LINKED ISSUE #253: Don't show Output window when viewing File History
When I open up File History with this extension, the Output window also appears. Is it possible to make it NOT appear when I view File History?

### PR DESCRIPTION
**Pull request by DonJayamanne**
Fixes #253

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@VamshiKrishnaAlladi I take that back, the code is correct. But I removed the `.catch(()=> undefined)`.
The `exec` throws an exception as well (not returned via a promise).
Either way, you have identified a problem. thanks.

**Comment by VamshiKrishnaAlladi** [comment]
But this doesn't fix the issue though.

**Comment by dipnlik** [comment]
@DonJayamanne I just downloaded the extension and the output window still appears when the repo has no `origin` remote, with a `fatal: No such remote 'origin'` error.

(sorry if this isn't the right place to comment)

**Comment by dustinmoris** [comment]
This issue is not fixed yet. Please check #281 for the real fix.

**Pull request merged**
