### PR TITLE
Lint vs gulp

### PR DESCRIPTION
**Pull request by ole1986**
I assume the reason of #455, #454 and #447 #448 is also to reduce such tools on developer side and automate it using Github action (or similar) during PR merge.

To be honest I did not know the reason of gulp and havent used it (except the hygiene check).
I always had the impression that this was kinda overdressed.

So what does this PR contain?

- Removed gulp
- Still use husky `tslint` during `git commit`
- Slightly amended the `tslint.json`
- `tslint --fix` the whole src/ directory while fixing the issue to become successful

Whats next?

- maybe run `typescript-formatter` locally on every commit?
- Recover code code coverage only through GitHub Action?

@DonJayamanne please let me know what you think about it.

### CODE REVIEW

**Comment by DonJayamanne** [comment]
I hated what u did with gulp as well.

**Comment by DonJayamanne** [comment]
> maybe run typescript-formatter locally on every commit?

I'd prefer to use eslint and prettier.

> Recover code code coverage only through GitHub Action?

use jest for coverage.

FYI. Please feel free to checkout the projects under https://github.com/DonJayamanne/gitHistoryVSCode/projects/2 and assign some to your self.

Once we have eslint, prettier and the like locally, we can move them to GitHub actions, separate phase/project https://github.com/DonJayamanne/gitHistoryVSCode/projects/4

**Summarizing:**
* eslint instead of tslint (start locally, then github actions)
* prettier instead of tsformat (start locally, then github actions)
* ts-jesst instead of istanbul/nyc/mocha (start locally, then github actions)

By start locally, i mean have scripts in package.json setup so we can use it locally, then when happy that things are ok, separate PR to get into github actions.

**Comment by ole1986** [comment]
I am not quite sure about jest. Since the only supported seem to be mocha (https://github.com/Microsoft/vscode/issues/67619#issuecomment-459254091)

At least i corrected the parser.test.ts in unit testing for fileStat

**Comment by ole1986** [comment]
Also, some tests may be unnecessary due to the use of vscode git extension. (E.g. RefsParser)

**Comment by DonJayamanne** [comment]
> Since the only supported seem to be

It is possible, that's an old comment, also I've used it
https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-runner-script

**Pull request merged**
