### PR TITLE
Typescript2

### PR DESCRIPTION
**Pull request by mikes-gh**
This rather large Pull request brings us into the typescript2 world.

Advantages
- Gets rid of all the typing stuff.
- Allows us to set some great `tsc` compiler options to tighten up the code.
- All imports .  No `requires` or `///` (triple slash)
- Future proof.

Changes
- No longer rely on `moment`.  The built in browser for vscode is chromium codebase so we have known behaviour.  Use `toUTCString()` for all dates.
- Strongly type low hanging fruit.  TODO: Some types were explicitly set to any to satisfy compiler. There is room for further strong typing.
- Remove unused variables.
- Generally rely on the `@types` packages which simplify module resolution.
- Move to `he` from `htmlencode` as it has `@types` package and has way more downloads as well.

Please note to test

`git clone https://github.com/mikes-gh/gitHistoryVSCode.git`
`cd gitHistoryVSCode`
`git checkout typescript2`
`npm install`
`npm run compile`

Open vscode in Repo folder above
F5 to test.

Tested so far on windows 7 and OSX 10.11.6

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@mikes-gh 
Wow, thanks will check this out and merge it in.

**Comment by mikes-gh** [comment]
Comments welcome.

**Comment by DonJayamanne** [comment]
@mikes-gh 
I don't think there's anything to comment on. The changes are quite simple. Will look into this tomorrow.

**Comment by mikes-gh** [comment]
toUTCString is bit verbose for the picklists.
Also maybe the picklist should have commit message first, author last.
I can address that in another PR.

**Comment by mikes-gh** [comment]
Id like to add a couple minor amendments .
Have you cloned yet?

Keep naming of htmlEncode as alias to he encode.
Fix small whitespace issue.

**Comment by mikes-gh** [comment]
Ok just updated aesthetic changes so low risk.

**Comment by mikes-gh** [comment]
OK Sorry found a bug in view commit details which needs specific date format.

**Comment by mikes-gh** [comment]
OK this is still work in progress dates wise.
Looks like toLocaleString  for dates is no good in vscde for en_GB as vscode only supports en_US.
Need to move to a locale agnostic date strategy.
Also toUTCString is no good either as everything is GMT (UTC)
I am sure I can fix but need a bit more time.

**Comment by mikes-gh** [comment]
An update 

The bug I am coming across is in master.

I am giving up tonight will look tomorrow.

**Comment by mikes-gh** [comment]
Still work in progress (nearly there) closing till I finish

**Comment by DonJayamanne** [comment]
Sorry for not replying, been busy, but was planning on merging this. Will leave it in your capable hands.

**Pull request closed without merging**
